### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by youquanl** [PRBonn/TARL#1]
Thanks for your nice work and open-source code! 

In the "utils/pcd_preprocess.py",  you used -np.inf as a delimiter to divide the aggregated point clouds,  so the points_set includes -np.inf as input for clusters_hdbscan function, it will raise the following error: "ValueError: Input contains NaN, infinity or a value too large for dtype('float64')."   Did you meet this problem while training?

**Comment by youquanl** [comment]
Hey, btw, how long did you spend to train one epoch at the pre-training stage?

**Comment by nuneslu** [comment]
Hi! Regarding the first error, it is probably due to a difference in the hdbscan version. Please try to use the one specified in the requirements.txt which is hdbscan==0.8.28

About the pre-training epoch, it took around 25 minutes per epoch, but the first epoch takes longer since it generates the clusters and then saves this assignment to be used in the following epochs. So overall, the first epoch may take a couple of hours but after this, the epochs should take around 30 minutes since all the clustering step results were saved in disk and now just need to be loaded.

**Comment by youquanl** [comment]
Hi! Thanks for your kind reply! The problem is solved with the right version of hdbscan.  Thanks again!
