### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by codename1995** [PRBonn/TARL#7]
Hi,

thank you for your great work. The idea is straightforward but works excellent. May I ask how do you evaluate your model performance on SemanticKITTI? Or do you have a recommendation for evaluation code repo?

**Comment by nuneslu** [comment]
Hi, thanks for the interest in our work! To evaluate our model we fine-tune it to semantic segmentation, object detection and panoptic segmentation, we have more information on this section of the readme: https://github.com/PRBonn/TARL#pre-trained-weights

Also, we refer to the segcontrast repo (https://github.com/PRBonn/segcontrast/blob/main/README.md) for the semantic segmentation evaluation.

**Comment by codename1995** [comment]
Nice! I miss that instruction. Thanks a lot.

**Comment by chenhaomingbob** [comment]
Hi @nuneslu, I am interested in the panoptic segmentation task. Can you tell me more details about transferring the pre-trained 3D backbone to panoptic segmentation? For example, why do you use the pre-trained MinkUnelt model as the 3D backbone instead of the VoxelNet implemented by the spconv, like in [DS-Net](https://github.com/hongfz16/DS-Net)?

If possible, can you share the panoptic segmentation codes with me?
